name: Deploy Health Dashboard

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > ~/devops-bootcamp/.env << EOF
            POSTGRES_DB=healthdb
            POSTGRES_USER=admin
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_HOST=db
            DB_NAME=healthdb
            DB_USER=admin
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF
      - name: Deploy to GCP server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/devops-bootcamp
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker compose ps
  notify-failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Send failure to n8n
        run: |
          curl -X POST http://34.93.85.189:5678/webhook/cicd-failure \
            -H "Content-Type: application/json" \
            -d '{"error": "GitHub Actions deployment failed for repo ${{ github.repository }} on branch ${{ github.ref_name }}"}'
